name: 'Upload Artifact'
description: 'Upload build artifacts to GitHub'
runs:
  using: 'composite'
  steps:
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-${{ env.PACKAGE_VERSION }}
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 90

    - name: Create artifacts directory
      shell: bash
      run: mkdir -p artifacts
      working-directory: ${{ github.workspace }}

    - name: Copy APK files to artifacts directory
      shell: bash
      run: |
        cp android/app/build/outputs/apk/release/app-arm64-v8a-release.apk artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-arm64-v8a.apk
        cp android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-armeabi-v7a.apk
        cp android/app/build/outputs/apk/release/app-x86_64-release.apk artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-x86_64.apk
        cp android/app/build/outputs/apk/release/app-x86-release.apk artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-x86.apk
        cp android/app/build/outputs/apk/release/app-universal-release.apk artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-universal.apk
        cp android/app/build/outputs/apk/release/app-arm64-v8a-release.apk artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-sl-arm64-v8a.apk
      working-directory: ${{ github.workspace }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./publish/changeLog.md
        prerelease: false
        draft: false
        tag_name: v${{ env.PACKAGE_VERSION }}
        files: |
          artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-arm64-v8a.apk
          artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-armeabi-v7a.apk
          artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-x86_64.apk
          artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-x86.apk
          artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-universal.apk
          artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-sl-arm64-v8a.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}